services:
  accessguard-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: accessguard-api
    ports:
      - "8000:8000"
    environment:
      ACCESSGUARD_DATABASE_PATH: /app/data/accessguard.db
      ACCESSGUARD_SECRET_KEY: accessguard-docker-demo-secret-change-in-production
      ACCESSGUARD_ALGORITHM: HS256
      ACCESSGUARD_TOKEN_EXPIRE_MINUTES: "60"
    volumes:
      - accessguard_data:/app/data
    restart: unless-stopped
    networks:
      - accessguard-net

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: accessguard-prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      - accessguard-api
    restart: unless-stopped
    networks:
      - accessguard-net

  grafana:
    image: grafana/grafana:11.2.0
    container_name: accessguard-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "false"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - accessguard-net

networks:
  accessguard-net:
    driver: bridge

volumes:
  accessguard_data:
  prometheus_data:
  grafana_data:
